# Generated by Django 2.1.2 on 2018-12-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20181013_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='url',
        ),
    ]
